name: Publicar no NPM

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js v23.4.0
        uses: actions/setup-node@v4
        with:
          node-version: '23.4.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Instalar dependências
        run: npm install

      - name: Publicar pacote
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: false